16 implement the gateway for connecting to the content provider
javadjafari1/MJMusicPlayer pull request #17
Opened 2023-10-13 12:49 UTC by mohammadyt9731

2023-10-16 19:51 UTC, javadjafari1 requested changes

2023-10-16 19:51 UTC, javadjafari1 commented on app/src/main/kotlin/ir/thatsmejavad/mjmusic/core/contentProvider/extension/ContentResolverExtensions.kt
> +    trySend(true)
isn't the cause of one extra observe?

2023-10-16 19:51 UTC, javadjafari1 commented on app/src/main/kotlin/ir/thatsmejavad/mjmusic/core/contentProvider/model/AlbumColumns.kt
> +data class AlbumColumns(
the entity is postFix for our database data classes. that would be so confusing.

2023-10-16 19:51 UTC, javadjafari1 commented on app/src/main/kotlin/ir/thatsmejavad/mjmusic/core/contentProvider/model/AudioColumns.kt
> +    val data: String?,// Path to the audio file.
the data is deprecated in api 29. and there is new way of getting file uri. this can be deleted.

2023-10-16 19:51 UTC, javadjafari1 commented on app/src/main/kotlin/ir/thatsmejavad/mjmusic/core/contentProvider/projection/AlbumProjection.kt
> +    val album = ALBUM_PROJECTION.indexOf(MediaStore.Audio.AlbumColumns.ALBUM)
i saw another way for getting the index of Column, getColumnIndex. you sure this is the correct way for getting ColumnIndex? this index is index of This item in the above list.

2023-10-16 19:51 UTC, javadjafari1 commented on app/src/main/kotlin/ir/thatsmejavad/mjmusic/core/contentProvider/provider/AudioProviderImpl.kt
> +        context.contentResolver.observeChanges(MediaStore.Audio.Media.EXTERNAL_CONTENT_URI)
i think you should differ between first data collecting and observing changes. there should be another function to return just the data not the Flow of data.

2023-10-19 11:20 UTC, mohammadyt9731 commented on app/src/main/kotlin/ir/thatsmejavad/mjmusic/core/contentProvider/projection/AlbumProjection.kt
> +    val album = ALBUM_PROJECTION.indexOf(MediaStore.Audio.AlbumColumns.ALBUM)
Your method using getColumnIndex is correct, but I've chosen to explicitly store the indices in AlbumProjectionIndexes for improved performance. It's a common practice for better efficiency when processing large datasets.

2023-10-21 18:12 UTC, mohammadyt9731 commented on app/src/main/kotlin/ir/thatsmejavad/mjmusic/core/contentProvider/extension/ContentResolverExtensions.kt
> +    trySend(true)
I thought that it was necessary to initiate the observation on the first try, but you're absolutely right. We should update the database whenever a change occurs

2023-10-21 18:24 UTC, javadjafari1 commented on app/src/main/kotlin/ir/thatsmejavad/mjmusic/core/contentProvider/extension/ContentResolverExtensions.kt
> +    trySend(true)
thanks.

2023-10-21 18:25 UTC, javadjafari1 commented on app/src/main/kotlin/ir/thatsmejavad/mjmusic/core/contentProvider/projection/AlbumProjection.kt
> +    val album = ALBUM_PROJECTION.indexOf(MediaStore.Audio.AlbumColumns.ALBUM)
wow great. did not know that.😇

2023-10-21 18:33 UTC, javadjafari1 approved these changes

2023-10-21 18:33 UTC, javadjafari1 commented on app/src/main/kotlin/ir/thatsmejavad/mjmusic/core/contentProvider/extension/CursorExternsions.kt
> +    isRingtone = getInt(AudioProjectionIndexes.isRingtone) != 0,
is there any column named `artwork` for the song? how should we get the song image?

2023-10-21 18:33 UTC, javadjafari1 commented on app/src/main/kotlin/ir/thatsmejavad/mjmusic/core/contentProvider/model/AudioColumns.kt
> +    val isDrm: String?,
whats the Drm full form?

2023-10-21 18:42 UTC, mohammadyt9731 commented on app/src/main/kotlin/ir/thatsmejavad/mjmusic/core/contentProvider/model/AudioColumns.kt
> +    val isDrm: String?,
Digital Rights Management (DRM)

2023-10-21 18:47 UTC, mohammadyt9731 commented on app/src/main/kotlin/ir/thatsmejavad/mjmusic/core/contentProvider/model/AudioColumns.kt
> +    val isDrm: String?,
```
In Android's MediaStore, the MediaStore.Audio.AudioColumns.IS_DRM is a column that indicates whether an audio file is protected by Digital Rights Management (DRM) or not. DRM is a technology used to restrict the usage and distribution of digital content, such as music, videos, and ebooks, to prevent unauthorized copying and sharing.

The IS_DRM column is a boolean flag that can have two possible values:

    0 - Indicates that the audio file is not protected by DRM, meaning it is a standard, non-DRM-protected audio file.
    1 - Indicates that the audio file is protected by DRM, which means it may have restrictions on how it can be played, copied, or shared, depending on the specific DRM system in use.

Developers can query the MediaStore to retrieve information about audio files, including whether they are DRM-protected or not, by checking the value in the IS_DRM column. This information can be useful for applications that want to handle audio files differently based on their DRM status.
```

2023-10-23 19:59 UTC, mohammadyt9731 commented on app/src/main/kotlin/ir/thatsmejavad/mjmusic/core/contentProvider/extension/CursorExternsions.kt
> +    isRingtone = getInt(AudioProjectionIndexes.isRingtone) != 0,
we can use this function to get the image of a song?

```
private fun getAlbumArt(context: Context, albumId: Long): ImageBitmap? {
    val albumArtUri = ContentUris.withAppendedId(
        Uri.parse("content://media/external/audio/albumart"), albumId
    )
    val inputStream = context.contentResolver.openInputStream(albumArtUri)
    inputStream?.use {
        val bitmap = BitmapFactory.decodeStream(it)
        return bitmap.asImageBitmap()
    }
    return null
}
```

2023-10-31 18:09 UTC, merged