14 implementing the bottom navigation in the app
javadjafari1/MJMusicPlayer pull request #18
Opened 2023-10-16 20:17 UTC by Mohammad-Taghizadeh

2023-10-18 19:14 UTC, javadjafari1 requested changes

2023-10-18 19:14 UTC, javadjafari1 commented on app/src/main/kotlin/ir/thatsmejavad/mjmusic/ui/bottombar/BottomBar.kt
> +    navController: NavController,
the item should not take the navController as parameter, a modifier and whether the item is selected or not. and some text and icon not the whole Item.

2023-10-18 19:14 UTC, javadjafari1 commented on app/src/main/kotlin/ir/thatsmejavad/mjmusic/ui/bottombar/BottomBar.kt
> +            .weight(if (selected) 1f else WEIGHT_7)
i don't know what this is needed? please elaborate.

2023-10-18 19:14 UTC, javadjafari1 commented on app/src/main/kotlin/ir/thatsmejavad/mjmusic/ui/bottombar/BottomBar.kt
> +                if (!selected) {
what?
why would this item checks if the item is selected or not?
if you don't want to navigate to current selected screen again you should use `launchSingleTop`.

2023-10-18 19:14 UTC, javadjafari1 commented on app/src/main/kotlin/ir/thatsmejavad/mjmusic/ui/bottombar/BottomBar.kt
> +                if (!selected) {
use the named argument style for the line 84.

2023-10-18 19:14 UTC, javadjafari1 commented on app/src/main/kotlin/ir/thatsmejavad/mjmusic/ui/bottombar/BottomBarItem.kt
> +    val icon: Int,
use  `@drawableRes` for drawable resources.

2023-10-18 19:14 UTC, javadjafari1 commented on app/src/main/kotlin/ir/thatsmejavad/mjmusic/ui/bottombar/BottomBarItem.kt
> +    val title: String,
use int type and `@stringRes` for string resources.

2023-10-18 19:14 UTC, javadjafari1 commented on app/src/main/kotlin/ir/thatsmejavad/mjmusic/ui/bottombar/BottomBarItem.kt
> +        title = "Home",
it should have the id of the resource. don't hardcode. 

2023-10-19 10:47 UTC, mohammadyt9731 commented on app/src/main/kotlin/ir/thatsmejavad/mjmusic/ui/bottombar/BottomBarItem.kt
> +        iconFocused = R.drawable.ic_bottom_bar_home_focused
I think focusedIcon is a better name instead of iconFocused

2023-10-30 21:19 UTC, Mohammad-Taghizadeh commented on app/src/main/kotlin/ir/thatsmejavad/mjmusic/ui/bottombar/BottomBar.kt
> +            .weight(if (selected) 1f else WEIGHT_7)
In order for the items to take the entire width of the page, we must use this, also to change the size of the clicked item.

2023-10-31 20:39 UTC, mohammadyt9731 commented on app/src/main/kotlin/ir/thatsmejavad/mjmusic/ui/bottombar/BottomBar.kt
> +            .heightIn(max = 44.dp)
i think we should use 'min' instead of 'max' for the height

2023-10-31 20:49 UTC, mohammadyt9731 commented on app/src/main/kotlin/ir/thatsmejavad/mjmusic/ui/bottombar/BottomBar.kt
> +    val weight = remember { Animatable(if (selected) 1f else WEIGHT_7) }
Why do we need 'weight'? It might not work well on small devices.

2023-11-03 15:43 UTC, javadjafari1 requested changes

2023-11-03 15:43 UTC, javadjafari1 commented on app/src/main/kotlin/ir/thatsmejavad/mjmusic/ui/bottombar/BottomBar.kt
> +fun BottomBar(
change the name to something unique that is specific to the App, this name cause the ambiguous problems.

2023-11-03 15:43 UTC, javadjafari1 commented on app/src/main/kotlin/ir/thatsmejavad/mjmusic/ui/bottombar/BottomBar.kt
> +    screens: List<BottomBarItem>,
it would be items not the whole screens

2023-11-03 15:43 UTC, javadjafari1 commented on app/src/main/kotlin/ir/thatsmejavad/mjmusic/ui/bottombar/BottomBarItem.kt
> +        val screens = listOf(
items would be a better name

2023-11-03 15:43 UTC, javadjafari1 commented on app/src/main/kotlin/ir/thatsmejavad/mjmusic/ui/bottombar/BottomBar.kt
> +    currentDestination: String?,
it would check the current Destination by item not the route.
the type should be BottomBarItem

2023-11-03 15:43 UTC, javadjafari1 commented on app/src/main/kotlin/ir/thatsmejavad/mjmusic/ui/bottombar/BottomBar.kt
> +    onItemClick: (String) -> Unit
it should return the BottomBar item

2023-11-03 15:43 UTC, javadjafari1 commented on app/src/main/kotlin/ir/thatsmejavad/mjmusic/ui/bottombar/BottomBar.kt
> +private fun RowScope.AddBottomBarItem(
the Composable function name should not be like order.

2023-11-03 15:43 UTC, javadjafari1 commented on app/src/main/kotlin/ir/thatsmejavad/mjmusic/ui/bottombar/BottomBar.kt
> +    val weight = remember { Animatable(if (selected) 1f else WEIGHT_7) }
as per patch i sent you we don't need any weight

2023-11-03 15:45 UTC, javadjafari1 commented on app/src/main/kotlin/ir/thatsmejavad/mjmusic/screens/search/SearchScreen.kt
> +}
add a line here to pass the detekt issue

2023-11-04 18:28 UTC, javadjafari1 approved these changes

2023-11-04 18:28 UTC, javadjafari1 commented on app/src/main/kotlin/ir/thatsmejavad/mjmusic/ui/bottombar/MJMusicBottomBar.kt
> +            painter = painterResource(icon),
we can change between these two icon by CrossFade animation.

2023-11-04 19:51 UTC, mohammadyt9731 submitted a review, later dismissed

2023-11-05 04:16 UTC, javadjafari1 commented on app/src/main/kotlin/ir/thatsmejavad/mjmusic/ui/bottombar/MJMusicBottomBar.kt
> +            label = stringResource(R.string.label_selected_item_animation)
No need to add this in the resourses

2023-11-05 18:16 UTC, javadjafari1 approved these changes

2023-11-05 18:21 UTC, merged