27 implement the player service
javadjafari1/MJMusicPlayer pull request #28
Opened 2023-11-23 19:18 UTC by mohammadyt9731

2023-11-24 16:38 UTC, javadjafari1 requested changes

2023-11-24 16:38 UTC, javadjafari1 commented on app/src/main/kotlin/ir/thatsmejavad/mjmusic/core/audioPlayer/AudioEvent.kt
> +    value class UpdateProgress(val progressMs: Long) : AudioEvent
I think using value class as Event would be wrong, the correct way would be like this

```kotlin
data class UpdateProgress(val progress: ProgressInMillis) : AudioEvent

value class ProgressInMillis(val value:Long)
```

2023-11-24 16:38 UTC, javadjafari1 commented on app/src/main/kotlin/ir/thatsmejavad/mjmusic/core/audioPlayer/AudioHandler.kt
> +class AudioHandler(private val player: ExoPlayer) {
I think it would be more testable if we have an interface for handling Audio event, and this class would be a implementation of that interface.

2023-11-30 05:57 UTC, javadjafari1 commented on app/src/main/kotlin/ir/thatsmejavad/mjmusic/di/AudioPlayerModule.kt
> +        AudioHandlerImpl(get())
can't we use bind here?

2023-11-30 05:58 UTC, javadjafari1 approved these changes

2023-11-30 15:48 UTC, Mohammad-Taghizadeh commented on app/build.gradle.kts
> +    implementation("androidx.media3:media3-session:1.1.1")
I think it is better to use version 1.2.0 stable because they made many changes and fixed a series of bugs.

2023-12-01 14:45 UTC, mohammadyt9731 commented on app/src/main/kotlin/ir/thatsmejavad/mjmusic/di/AudioPlayerModule.kt
> +        AudioHandlerImpl(get())
Yes, we can! Using bind would increase flexibility and maintainability, separating the interface from its implementation. It allows for easier swapping of implementations without changing dependent classes. Let's leverage it for a more adaptable design

2023-12-01 19:08 UTC, merged